# Note: SciTools/cartopy is managed by a separate development team so is not
#  included in the templating.

SciTools/iris@demo_20230817_main:
  - source: templates/.pre-commit-config.yamll
    dest: .pre-commit-config.yamll
