# Note: SciTools/cartopy is managed by a separate development team so is not
#  included in the templating.

SciTools/cf-units:
  - source: templates/.pre-commit-config.yaml
    dest: .pre-commit-config.yaml
SciTools/iris:
  - source: templates/.pre-commit-config.yaml
    dest: .pre-commit-config.yaml
SciTools/iris-grib:
  - source: templates/.pre-commit-config.yaml
    dest: .pre-commit-config.yaml
SciTools/mo_pack:
  - source: templates/.pre-commit-config.yaml
    dest: .pre-commit-config.yaml
SciTools/nc-time-axis:
  - source: templates/.pre-commit-config.yaml
    dest: .pre-commit-config.yaml
SciTools/python-stratify:
  - source: templates/.pre-commit-config.yaml
    dest: .pre-commit-config.yaml
SciTools/tephi:
  - source: templates/.pre-commit-config.yaml
    dest: .pre-commit-config.yaml
SciTools/test-iris-imagehash:
  - source: templates/.pre-commit-config.yaml
    dest: .pre-commit-config.yaml
SciTools/workflows:
  - source: templates/.pre-commit-config.yaml
    dest: .pre-commit-config.yaml