name: Sync template files across repos
on:
  schedule:
    # "At 02:00 on day-of-month 1 in every 2nd month."
    - cron: '0 2 1 */2 *'
  workflow_dispatch:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: BetaHuhn/repo-file-sync-action@3023dac7ce66c18b119e2012348437eadeaea116
        with:
          GH_PAT: ${{ secrets.DEMO_SYNC }}
          CONFIG_PATH: .github/template-sync.yml
          PR_LABELS: |
            Bot
            Type: Infrastructure
          COMMIT_PREFIX: 👁 Template deviations
          PR_BODY: "https://github.com/SciTools/.github/tree/main/templates"
