name: Sync template files across repos
on:
  schedule:
    # "At 02:00 on day-of-month 1 in every 2nd month."
    - cron: '0 2 1 */2 *'
  workflow_dispatch:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: rasa/repo-file-sync-action@011c52e270cef47e3ed9af0a7a661d202acb1c72
        with:
          GH_PAT: ${{ secrets.DEMO_SYNC }}
          CONFIG_PATH: .github/workflows/template-sync.yml
          PR_LABELS: |
            Bot
            Type: Infrastructure
          COMMIT_PREFIX: 👁 Template deviations
          PR_BODY: https://github.com/SciTools/.github/tree/main/templates
