name: Sync template files across repos
on:
  schedule:
    # "At 02:00 on day-of-month 1 in every 2nd month."
    - cron: '0 2 1 */2 *'
  workflow_dispatch:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Skyvern-AI/repo-file-sync-action@07a31547d9400a3fdbb08fc8ae92243913bdfea5
        with:
          GH_PAT: ${{ secrets.DEMO_SYNC }}
          CONFIG_PATH: .github/workflows/template-sync.yml
          PR_LABELS: |
            Bot
            Type: Infrastructure
          PR_TITLE: 👁 Template deviations
          PR_BODY: https://github.com/SciTools/.github/tree/main/templates
